### ISSUE TITLE
ACK队列在项目中作用

### ISSUE THREAD

**Issue by tajinshi** [liushaoming/jseckill#1]

**Comment by liushaoming** [comment]
Ack， 这里设置autoAck=fals，为消费端手动应答（Acknowledge）。
当消费端读取到一条消息后， 处理自己的逻辑，如果处理成功，则执行
` channel.basicAck(envelope.getDeliveryTag(), false)` ,mq会自动把这条消息从mq中删除
如果消费端处理逻辑失败。应该执行`channel.basicNack(envelope.getDeliveryTag(), false, true)`
把这条消息退回到mq中。
同样，生产者发送消息的时候，也是最好设置手动confirm模式。
这样可以确保消息不丢失，数据不错乱.
