### ISSUE TITLE
先插入秒杀记录再减库存 updateInventory 方法 

### ISSUE THREAD

**Issue by afuchrisma** [liushaoming/jseckill#20]
先插入秒杀记录再减库存 updateInventory 方法 这个方法 mqcusmer消费的时候 调用吗 没看到调用逻辑
![Uploading 图片.png…]()

**Comment by bootsrc** [comment]
我的代码里并没有更新DB里的库存。 这个有待开发者自己去完成。
因为在redis里减库存，属于并发比较高的操作。 

后面真正付款的人，去见库存，数量相对少，并发相对少。开发者可以自行去完成。😄

**Comment by afuchrisma** [comment]
嗯 支付成功扣减库存没有问题。
我意思是 未支付的订单记录什么时候入库 也是在支付的时候跟减库存一起操作了是吗。
还是说未支付的订单 只查询redis里面的数据。

**Comment by afuchrisma** [comment]
另外 还有30分钟未支付过期 没看到代码哪里有体现呢

        jedis.decr(inventoryKey);
        jedis.sadd(boughtKey, String.valueOf(userPhone));

**Comment by afuchrisma** [comment]
订单过期单独设置了1个key 设置过期时间
        jedis.decr(inventoryKey);
        jedis.sadd(boughtKey, String.valueOf(userPhone));
        jedis.set(expiredKey, "","NX", "EX", 180);
然后加监听更新库存
<img width="674" alt="图片" src="https://user-images.githubusercontent.com/17420690/104568629-4865b500-568b-11eb-89d1-5e5bebbe4b1e.png">
